#INCLUDE <P16F887.INC>
 LIST P=16F887
; CONFIG1
; __config 0xFFE1
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
 CBLOCK 0x20
 ENDC
 ORG 0
 SETUP:
    CALL RETARDO_2S_16
    CALL IRsetup
    MOVLW 0xFF
    CALL IRcarrier
    MOVLW D'146'	;9ms de carrier
    CALL IRcarrier
 START:
    CALL RETARDO_500MS_16
    BSF PORTD, 0
    CALL RETARDO_500MS_16
    BCF PORTD, 0
    GOTO START
    #INCLUDE <RETARDOS.inc>
    #INCLUDE <RETARDOS_16MHZ.inc>
    #INCLUDE <LCD.inc>
    #INCLUDE <IR.inc>
 END


