    CBLOCK
    memocaracter
    memoriaw
    caractertemp
    ENDC

DATOS EQU PORTD	    ;LINEAS DE DATOS
PINLCD EQU PORTD    ;LINEAS DE CONTROL
 
RS EQU 1    ;LINEA DE CONTROL RS 
RW EQU 2	;LINEA DE CONTROL RW
E EQU 3	;LINEA DE OCNTROL E
 
ON_DISPLAY_CURSOR_BLINK EQU 0FH	;ACTIVA EL DISPLAY, EL CURSOR Y HACE PARPADEO
SOLO_DISPLAY EQU 0CH		;APAGA EL CURSOR Y SU PARPADEO
LIMPIAR_LCD	EQU 01H			;LIMPIA LOS CARACTERES DE LA PANTALLA
APAGAR_DISPLAY  EQU 08H		;APAGA LA PANTALLA
SALTO_ENTER EQU C0H			;SE DIRIGE A LA SEGUNDA LINEA
HOME_INICIO EQU 02H			;VUELVE AL INICIO
MOVER_CURSOR_IZQ EQU 10H		;MUEVE EL CURSOR A LA IZQUIERDA
MOVER_CURSOR_DERECHA EQU 14H	;MUEVE EL CURSOR A LA DERECHA
MOVER_PANTALLA_IZQ EQU 18H		;MUEVE LA PANTALLA A LA IZQUIERDA
MOVER_PANTALLA_DERECHA EQU 1CH	;MUEVE LA PANTALLA A LA DERECHA
OFF EQU 0
ON EQU 1

 INICIALIZACION_DE_PANTALLA
    CALL RETARDO_20MICROS
    RETURN


