#INCLUDE <P16F887.INC>
LIST P=16F887
#INCLUDE <MACROS.INC>
; CONFIG1
; __config 0xEFC2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
 CBLOCK 0x20
    DIGITO
    TEMP
    COUNTER
    REC_BYTE1
    REC_BYTE2
ENDC

ORG 0
SETUP:
	CALL irinit
	LCD_INIT
	;MOVLW 0x7A
	;MOVWF REC_BYTE1
	;MOVLW 0x9A
	;MOVWF REC_BYTE2 
START:
	WRITE_LCD 'C'
	WRITE_LCD 'O'
	WRITE_LCD 'D'
	WRITE_LCD 'I'
	WRITE_LCD 'G'
	WRITE_LCD 'O'
	WRITE_LCD ':'
	MOVFW REC_BYTE1
	MOVWF TEMP
	CALL IMPRIMIR_VAR
	MOVFW REC_BYTE2
	MOVWF TEMP
	CALL IMPRIMIR_VAR
	ORIGIN_LCD
	ONLY_DISPLAY
	GOTO START

IMPRIMIR_VAR:
    INCF COUNTER
    MOVLW D'9'
    MOVWF DIGITO
    SWAPF TEMP,1
    MOVFW TEMP
    ANDLW 0xF
    SUBWF DIGITO,1
    BTFSC STATUS,C
    GOTO DECIMAL
    GOTO HEXADECIMAL
DECIMAL:
    ;ADDLW '0'
    MOVWF DIGITO
    WRITE_LCD_REG DIGITO
    GOTO VERIFICACION
HEXADECIMAL:
    ;ADDLW D'55'
    MOVWF DIGITO
    WRITE_LCD_REG_HEX DIGITO
VERIFICACION:
    MOVLW D'2'
    SUBWF COUNTER,0
    BTFSS STATUS,Z
    GOTO IMPRIMIR_VAR
    CLRF COUNTER
    RETURN
    
; setup for IR reception
irinit: 
	BSF STATUS,RP0
	BSF STATUS,RP1
	CLRF ANSEL
	CLRF ANSELH
	BSF STATUS,RP0
	BCF STATUS,RP1
	BSF PORTB,4   ; IR is input
	CLRF TRISD
	BCF STATUS,RP0      ; Select memory bank 0
	CLRF	PORTD
	RETURN

	#INCLUDE <RETARDOS.inc>
	#INCLUDE <LCD20X4.inc>
	#INCLUDE <BCD.INC>
	END


