    PROCESSOR 16F887
    #INCLUDE <P16F887.INC>
    LIST P=16F887
    ; CONFIG1
    ; __config 0xFFE2
     __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
    ; CONFIG2
    ; __config 0xFFFF
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    CBLOCK 0x00
    ENDC
    ORG 0
INICIO
    BSF STATUS,RP0  
    BCF STATUS,RP1
    MOVLW B'00000000'
    MOVWF TRISD
    BCF STATUS, RP0
    BCF STATUS, RP1
    CALL RETARDO_5S
    BSF PORTD,0
    CALL RETARDO_5S
    BCF PORTD,0
    GOTO INICIO
    #INCLUDE <RETARDOS.INC>
    END

