#INCLUDE <P16F887.INC>
    LIST P=16F887
; CONFIG1
; __config 0xFFE1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 CBLOCK
    CONTADOR
    DUTY_ON
    DUTY_OFF
 ENDC
    PERIODO EQU .300
  ;RC2 -> CCP1 PWM
  ;RA0 -> AN0 POT_IN
 
 ORG 0
 CONFIGURACION
    BSF STATUS, RP0
    BCF STATUS, RP1	;BANCO 1.
    BCF TRISC, 2	;RC2 -> CCP1 COMO SALIDA.
    BSF TRISA, 0	;RA0 -> AN0 COMO ENTRADA.
    ;CONFIGURACION ADC
    BSF STATUS, RP0	
    BSF STATUS, RP1	;BANCO 3.
    BSF ANSEL, 0	;AN0 ES DECLARADO COMO ENTRADA ANALOGICA.
    CLRF ANSELH		;TODOS LO PINES DIFERENTES A AN0 SON DIGITALES.
    BSF STATUS, RP0
    BCF STATUS, RP1	;BANCO 1.
    CLRF ADCON1		;JUSTIFICACION A LA IZQUIERDA.
    BCF STATUS, RP0	;BANCO 0.
 INICIO
    MOVLW B'00000001'	;FOSC/2, AN0, ADC ENABLE 0.
    MOVWF ADCON0;
    BCF PIR1, ADIF	;SE RESTAURA EL FLAG DEL ADC.
 DELAY
    MOVLW D'19'
    MOVWF CONTADOR
 DELAY_BUCLE
    DECFSZ CONTADOR, 1
    GOTO DELAY_BUCLE	
    BSF ADCON0, GO	;EL ADC EMPIEZA CON LA CONVERSION.
 ADC_INICIO
    BTFSS PIR1, ADIF	;PREGUNTA SI SE ACABO CON LA CONVERSION.
    GOTO ADC_INICIO
    MOVF ADRESH, W
    MOVWF DUTY_ON	;REGISTRA EL VALOR PARA EL PERIODO.
    BSF STATUS, RP0	;BANCO 1.
    RRF ADRESL, F	;HACE UN CORRIMIENTO A LA DERECHA AUMENTANDO 1.
    RRF ADRESL, W
    BCF STATUS, RP0	;BANCO 0.
    ANDLW B'00110000'
    MOVWF DUTY_OFF
 CONFIGURACION_PWM
    MOVLW B'00001100'
    IORWF DUTY_OFF, F	;SE OBTIENEN LOS VALORES DE DUTY_OFF.
    MOVWF CCP1CON	;MODO PWM PARA CCP1.
    ;REGISTRO PR2
    MOVLW PERIODO-1
    BSF STATUS, RP0	;BANCO 1.
    MOVWF PR2
    BCF STATUS, RP0	;BANCO 0.
    ;ANCHURA DE PULSO
    MOVF DUTY_ON, W
    MOVWF CCPR1L
    ;PRESCALER
    MOVLW B'00000101'
    MOVWF T2CON
    GOTO INICIO
 END