#INCLUDE <P16F887.INC>
    LIST P=16F887
; CONFIG1
; __config 0xEFC2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
 udata
 
 CBLOCK 0x20
 BOTON
 ENDC
 
 ORG 0
 SETUP:
    BSF STATUS,RP0
    BCF STATUS,RP1	;BANCO 1.
    BCF TRISC,6 
    BSF TRISC,7
    MOVLW D'00000111'
    MOVWF TRISD
    MOVLW D'25'		;2400 BAUDIOS.
    MOVWF SPBRG
    MOVLW B'00100000'
    MOVWF TXSTA
    BCF STATUS,RP0	;BANCO 0.
    CLRF PORTD
    MOVLW B'10010000'
    MOVWF RCSTA
    MOVLW D'00110000'
    MOVWF T1CON
 PROGRAMA:
    MOVLW 0x00
    BTFSC PORTD,0
    MOVLW 0x55
    BTFSC PORTD,1
    MOVLW 0xAA
    BTFSC PORTD,2
    MOVLW 0xFF
    MOVWF TXREG
    GOTO PROGRAMA
    END