    PROCESSOR 16F887
    #INCLUDE <P16F887.INC>
    LIST P=16F887
    ; CONFIG1
    ; __config 0xFFE1
    __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
    ; CONFIG2
    ; __config 0xFFFF
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    #DEFINE RED PORTD,0
    #DEFINE GREEN PORTD,1
    #DEFINE BLUE PORTD,2
    
    UDATA
    
    CBLOCK 0x20
    CONTADOR
    ENDC
    
    ORG 0
    GOTO SETUP
    ORG 4
    GOTO INTERRUPCION
 SETUP:
    BSF STATUS,RP0	    ;BANCO 1.
    BCF STATUS, RP1
    BCF TRISC,2
    BSF TRISA,4
    CLRF TRISD
    BCF OPTION_REG,NOT_RBPU ;PULL UP PORTB
    BCF OPTION_REG,INTEDG   ;FLANCO DESCENDENTE INT.
    MOVLW D'249'
    MOVWF PR2
    BSF STATUS,RP1	    ;BANCO 3.
    CLRF ANSEL
    CLRF ANSELH
    BCF STATUS,RP0	    ;BANCO 0.
    BCF STATUS,RP1
    MOVLW B'10010000'
    MOVWF INTCON
    MOVLW B'00001100'
    MOVWF CCP1CON
    MOVLW D'125'
    MOVWF CCPR1L
    CLRF PORTD
    MOVLW 0x00
    MOVWF CONTADOR
 PROGRAMA:
    BTFSC PORTA,4
    GOTO BOTON_PRESIONADO
    GOTO PROGRAMA
BOTON_PRESIONADO:
    BTFSC PORTA,4
    GOTO BOTON_PRESIONADO
    MOVLW D'1'
    ADDWF CONTADOR,1
    MOVFW CONTADOR
    ANDLW D'7'
    MOVWF PORTD
    GOTO PROGRAMA
    
    CBLOCK
    GUARDA_W
    GUARDA_STATUS
    ENDC
    
 INTERRUPCION:
    MOVWF GUARDA_W
    SWAPF STATUS,W
    MOVWF GUARDA_STATUS
    BCF STATUS,RP0
    BCF STATUS,C
    ;COMIENZO INTERRUPCION:
    MOVLW D'31'
    ADDWF CCPR1L,1
 FIN_INTERRUPCION:
    SWAPF GUARDA_STATUS,W
    MOVWF STATUS
    SWAPF GUARDA_W,F
    SWAPF GUARDA_W,W
    BCF INTCON,INTF
    RETFIE
    END

